### PR TITLE
Fixing envelop bug

### LINKED ISSUE #38: segfault in latest release on `envelop` command
Working through the steps in the [docs](https://docs.gobl.org/quick-start/invoices), there appears to be a segfault when trying to envelop.

Command:

```
gobl envelop -t bill.Invoice -i invoice.yaml
```

Output:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x2 pc=0x10539e440]

goroutine 1 [running]:
main.(*rootOpts).openOutput(0x0, 0x1400032ca00, {0x140002dfe40, 0x1, 0x4})
	/Users/sam/go/pkg/mod/github.com/invopop/gobl.cli@v0.26.0/cmd/gobl/root.go:66 +0x20
main.(*buildOpts).runE(0x140000cff80, 0x1400032ca00, {0x140002dfe40, 0x1, 0x4})
	/Users/sam/go/pkg/mod/github.com/invopop/gobl.cli@v0.26.0/cmd/gobl/build.go:92 +0x18c
github.com/spf13/cobra.(*Command).execute(0x1400032ca00, {0x140002dfe00, 0x4, 0x4})
	/Users/sam/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x668
github.com/spf13/cobra.(*Command).ExecuteC(0x1400032c500)
	/Users/sam/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x410
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/sam/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/Users/sam/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:895
main.run()
	/Users/sam/go/pkg/mod/github.com/invopop/gobl.cli@v0.26.0/cmd/gobl/main.go:43 +0x118
main.main()
	/Users/sam/go/pkg/mod/github.com/invopop/gobl.cli@v0.26.0/cmd/gobl/main.go:20 +0x20
```

### PR DESCRIPTION
**Pull request by samlown**
Fixes #38

### CODE REVIEW

File: cmd/gobl/root.go [hunk 1]
```diff
@@ -20,21 +20,20 @@ func root() *rootOpts {
 }
 
 func (o *rootOpts) cmd() *cobra.Command {
-	opts := &rootOpts{}
```
Comment (samlown) [inline cmd/gobl/root.go:23]: I wasn't sure why this new instance of `rootOpts` was being created.

**Review by flimzy — APPROVED** [review]
